In [1]:
import time
import pandas as pd
import numpy as np

survey = pd.read_csv(r'output.csv')

def sigmoid_der(x):
    return x * (1-x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [2]:
survey

Name  Strength    Vision  Outcome
0        52   3.89003  1.019580        1
1        55   3.88758  0.965534        1
2        46   3.89121  1.021750        1
3        50   3.84449  1.022640        1
4        57   3.84475  0.952833        1
...     ...       ...       ...      ...
37400    26   2.45580  2.416850        0
37401    27   2.38736  2.309400        0
37402    28   2.35830  2.387700        0
37403    30   2.34689  2.388490        0
37404    31   2.38398  2.297690        0

[37405 rows x 4 columns]

In [3]:
input_in = survey.drop(columns=["Name","Outcome"])

In [4]:
input_in_np = input_in.to_numpy()
input_in_np = input_in_np / 5
input_in_np

array([[0.778006 , 0.203916 ],
       [0.777516 , 0.1931068],
       [0.778242 , 0.20435  ],
       ...,
       [0.47166  , 0.47754  ],
       [0.469378 , 0.477698 ],
       [0.476796 , 0.459538 ]])

In [5]:
output_in = survey.drop(columns=["Name","Strength","Vision"])

In [6]:
output_in_np = output_in.to_numpy()
output_in_np

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [9]:
np.random.seed(int(time.time()))

weights = 2 * np.random.random((2,1)) - 1

for i in range(1000):
    output = sigmoid(np.dot(input_in_np, weights))
    error = output_in_np - output
    adj = error * sigmoid_der(output)
    weights += np.dot(input_in_np.T, adj)

print(weights)

[[-1794.21234959]
 [-1976.65929659]]


In [10]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [11]:
keras_data = survey.drop(columns=["Name"]).to_numpy()

In [12]:
model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
model.fit(input_in_np, output_in_np, epochs=10, batch_size=10, verbose=0)

In [15]:
predictions = model.predict_classes(input_in_np)

In [16]:
print(predictions)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
